---
- include_tasks:                'pi.yml'
- include_tasks:                '../tasks/system_groups.yml'
- include_tasks:                '../tasks/system_users.yml'
- include_tasks:                '../tasks/add_users_to_groups.yml'
#- include_tasks:                'storage.yml'
- include_tasks:                '../tasks/create_files.yml'
- include_tasks:                '../tasks/install_packages.yml'
- include_tasks:                '../tasks/lines_in_files.yml'
- include_tasks:                'mask.yml'
- include_tasks:                '../tasks/enable_services.yml'
- include_tasks:                '../tasks/restart_services.yml'
  when:                         install_packages_result.changed 
                                or lines_in_files_result.changed
                                or add_users_to_groups_result.changed
                                or install_files_result.changed
