---
- include:                      'storage.yml'
- include:                      'pi.yml'
- include:                      '../tasks/install_packages.yml'
- include:                      '../tasks/create_files.yml'
  vars:
    create_files:               "{{ create_files_phase_2 }}"
- include:                      '../tasks/lines_in_files.yml'
- include:                      '../tasks/enable_services.yml'
- include:                      '../tasks/restart_services.yml'
  when:                         install_packages_result.changed or lines_in_files_result.changed
