---
- include:                      'pi.yml'
- include:                      '../tasks/system_groups.yml'
- include:                      '../tasks/system_users.yml'
- include:                      '../tasks/add_users_to_groups.yml'
#- include:                      'storage.yml'
- include:                      '../tasks/create_files.yml'
- include:                      '../tasks/install_packages.yml'
- include:                      '../tasks/lines_in_files.yml'
- include:                      'mask.yml'
- include:                      '../tasks/enable_services.yml'
- include:                      '../tasks/restart_services.yml'
  when:                         install_packages_result.changed 
                                or lines_in_files_result.changed
                                or add_users_to_groups_result.changed
