---
- include_tasks:                '../tasks/lines_in_files.yml'
  vars:
    lines_in_files:             "{{ pi_lines_in_files }}"
- include_tasks:                '../tasks/reboot.yml'
  when:                         lines_in_files_result.changed
